# 블록체인 데이터가 저장될 데이터 경로
data-path = "/opt/besu/node/data"  # 실행 위치를 기준으로 한 상대경로

# 사용자 정의 genesis 파일의 경로이다.
genesis-file = "/opt/besu/genesis/genesis.json"

# Network identifier
network-id = 123

# p2p
p2p-host="0.0.0.0"
p2p-port=30305

# rpc
rpc-http-enabled = true
rpc-http-port=28545
rpc-http-api = ["ETH", "NET", "CLIQUE"] # List of enabled RPC HTTP APIs
rpc-http-cors-origins = ["all"] # Allowed CORS origins for HTTP
host-allowlist = ["*"] # Allowed hosts for HTTP access


# Enable the GraphQL HTTP service
graphql-http-enabled=true
graphql-http-port=28547

bootnodes = ["enode://4a3992c316d9ceefac5d3884ca10213059e561d09cdb2849f0357127a0738d8f03cab45170b3ae2eccc751f8afc4fa340d78d01d6ceae76201a86b6d6a62b953@172.18.0.2:30303"]

