# 블록체인 데이터가 저장될 데이터 경로
data-path = "/opt/besu/config/besudata"  # 실행 위치를 기준으로 한 상대경로

# 사용자 정의 genesis 파일의 경로이다.
genesis-file = "/opt/besu/config/genesis.json"

# Network identifier
network-id = 123

# Enable the RPC HTTP service
rpc-http-enabled = true

# List of enabled RPC HTTP APIs
rpc-http-api = ["ETH", "NET", "CLIQUE"]

# Allowed hosts for HTTP access
host-allowlist = ["*"]

# Allowed CORS origins for HTTP
rpc-http-cors-origins = ["all"]

# Enable the GraphQL HTTP service
graphql-http-enabled = true