# version '3.9'

networks:
  custom_bridge: # docker compose는 name을 유니크하게 유지하게 하기 위해, 현재 폴더명을 네트워크 이름 앞에 붙임
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:
  Node-1:
    image: hyperledger/besu:24.9.1
    container_name: Node-1
    networks: 
      custom_bridge:
        ipv4_address: 172.18.0.2
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8547:8547"
    volumes:
      - ./Node-1:/opt/besu/node
      - ./genesis:/opt/besu/genesis
    command: --config-file=/opt/besu/node/config.toml
  Node-2:
    image: hyperledger/besu:24.9.1
    container_name: Node-2
    networks:
      custom_bridge:
        ipv4_address: 172.18.0.3
    ports:
      - "30304:30303"
      - "18545:8545"
      - "18547:8547"
    volumes:
      - ./Node-2:/opt/besu/node
      - ./genesis:/opt/besu/genesis
    command: --config-file=/opt/besu/node/config.toml
  Node-3:
    image: hyperledger/besu:24.9.1
    container_name: Node-3
    networks:
      custom_bridge:
        ipv4_address: 172.18.0.4
    ports:
      - "30305:30303"
      - "28545:8545"
      - "28547:8547"
    volumes:
      - ./Node-3:/opt/besu/node
      - ./genesis:/opt/besu/genesis
    command: --config-file=/opt/besu/node/config.toml