log:
  level: 0 # 0: TRACE, 1: DEBUG, 2: INFO, 3: WARN, 4: ERROR, 5: FATAL, 6: PANIC, 7: NOLEVEL, 8: DISABLED

api:
  app-name: solana-workspace
  version: 0.0.0
  port: 58080

solana:
  rpc_url: http://124.50.46.159:50001 #http://localhost:8899
  ws_url: ws://124.50.46.159:50002 #ws://localhost:8900
  commitment: confirmed #finalized
  sync: true

wallet:
  N : 10
  M : 50