log:
  level: 0 # 0: TRACE, 1: DEBUG, 2: INFO, 3: WARN, 4: ERROR, 5: FATAL, 6: PANIC, 7: NOLEVEL, 8: DISABLED

api:
  app-name: solana-workspace
  version: 0.0.0
  port: 58080

solana:
  rpc_url: http://124.50.46.159:50001 #http://localhost:8899
  ws_url: ws://124.50.46.159:50002 #ws://localhost:8900
  commitment: confirmed #finalized
  sync: true
  timeout: 1 # 분단위 사용 0일 때 타임아웃 없음

wallet:
  T : 10 # wallets.txt에 사전 세팅 해두는 전체 계정 수
  N : 10
  M : 10