# 블록체인 데이터가 저장될 데이터 경로
data-path = "/opt/besu/node/data"  # 실행 위치를 기준으로 한 상대경로

# 사용자 정의 genesis 파일의 경로이다.
genesis-file = "/opt/besu/genesis/genesis.json"

# Network identifier
network-id = 123

# p2p
p2p-host="0.0.0.0"
p2p-port=30304

# rpc
rpc-http-enabled = true
rpc-http-port=18545
rpc-http-api = ["ETH", "NET", "CLIQUE"] # List of enabled RPC HTTP APIs
rpc-http-cors-origins = ["all"] # Allowed CORS origins for HTTP
host-allowlist = ["*"] # Allowed hosts for HTTP access


# Enable the GraphQL HTTP service
graphql-http-enabled=true
graphql-http-port=18547

bootnodes = ["enode://7009b59ba2e485b776de7fd4279fec3d8ca64383f4b4e7fe1d99fccc063ed1444590d205cb07c9ff0f1750f6628dd368e5cff08c1543f7efbf7bc7c3cc329712@172.18.0.2:30303"]

