# 블록체인 데이터가 저장될 데이터 경로
data-path = "/opt/besu/node/data"  # 실행 위치를 기준으로 한 상대경로

# 사용자 정의 genesis 파일의 경로이다.
genesis-file = "/opt/besu/node/genesis.json"

# Network identifier
network-id = 123

# p2p
p2p-host="0.0.0.0"
p2p-port=30303

# rpc
rpc-http-enabled = true
rpc-http-port=8545
rpc-http-api = ["ETH", "NET", "CLIQUE"] # List of enabled RPC HTTP APIs
rpc-http-cors-origins = ["all"] # Allowed CORS origins for HTTP
host-allowlist = ["*"] # Allowed hosts for HTTP access


# Enable the GraphQL HTTP service
graphql-http-enabled=true
graphql-http-port=8547

