// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/balance": {
            "get": {
                "description": "SOL Balance를 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/account"
                ],
                "summary": "solana balance query",
                "parameters": [
                    {
                        "description": "Get SOL Balance",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.TargetSolBalanceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/parameters.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/parameters.TokenBalanceRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/spl/deploy": {
            "post": {
                "description": "SPL Token을 생성합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/spl"
                ],
                "summary": "SPL Token 생성",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/parameters.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/parameters.PerformanceCreateSPLTokenRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/spl/deploy-with-mint": {
            "post": {
                "description": "Token Account를 생성한 뒤 민팅합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/spl"
                ],
                "summary": "Token Account 생성 후 민팅",
                "parameters": [
                    {
                        "description": "Performance Create SPL Token And Mint Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.CreateTokenWithMintReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/parameters.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/parameters.PerformanceCreateSPLTokenRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/spl/mint": {
            "post": {
                "description": "배포 완료 상태에서 target wallet에 추가 민팅합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/spl"
                ],
                "summary": "민팅",
                "parameters": [
                    {
                        "description": "Performance Create SPL Token Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.PerformanceMintReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/parameters.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/parameters.PerformanceMintRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/spl/query": {
            "get": {
                "description": "Token Balance를 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/spl"
                ],
                "summary": "Token Query",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/parameters.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/parameters.TokenBalanceRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/spl/set-mint-account": {
            "post": {
                "description": "기존 생성한 Mint Account에 deploy 후 민팅",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/spl"
                ],
                "summary": "테스트 사전 준비",
                "parameters": [
                    {
                        "description": "Performance Create SPL Token And Mint Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.CreateTokenWithMintReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/parameters.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/parameters.PerformanceMintRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/spl/target_query": {
            "get": {
                "description": "Token Balance를 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/spl"
                ],
                "summary": "Token Query",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/parameters.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/parameters.TokenBalanceRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/spl/transfer": {
            "post": {
                "description": "Token을 전송합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/spl"
                ],
                "summary": "Token Transfer",
                "parameters": [
                    {
                        "description": "Transfer SPL Token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.TransferTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/parameters.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/parameters.PerformanceMintRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "parameters.CommonResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "parameters.CreateTokenWithMintReq": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "PayerPrivateKey string ` + "`" + `json:\"payer_private_key\"` + "`" + `\nMintAccount     string ` + "`" + `json:\"mint_account\"` + "`" + `\nMintAuthority   string ` + "`" + `json:\"mint_authority\"` + "`" + `",
                    "type": "integer"
                }
            }
        },
        "parameters.PerformanceCreateSPLTokenRes": {
            "type": "object",
            "properties": {
                "mint_account": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "parameters.PerformanceMintReq": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "PayerPrivateKey string ` + "`" + `json:\"payer_private_key\"` + "`" + `\nMintAccount     string ` + "`" + `json:\"mint_account\"` + "`" + `\nMintAuthority   string ` + "`" + `json:\"mint_authority\"` + "`" + `",
                    "type": "integer"
                }
            }
        },
        "parameters.PerformanceMintRes": {
            "type": "object",
            "properties": {
                "signature": {
                    "type": "string"
                }
            }
        },
        "parameters.TargetSolBalanceReq": {
            "type": "object",
            "properties": {
                "owner_account": {
                    "type": "string"
                }
            }
        },
        "parameters.TokenBalanceRes": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string"
                },
                "mint_account": {
                    "type": "string"
                },
                "owner_account": {
                    "type": "string"
                }
            }
        },
        "parameters.TransferTokenReq": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "SOL API",
	Description:      "This is a rest api server for solapi",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
