basePath: /api/v1
definitions:
  parameters.CommonResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  parameters.CreateTokenWithMintReq:
    properties:
      amount:
        description: |-
          PayerPrivateKey string `json:"payer_private_key"`
          MintAccount     string `json:"mint_account"`
          MintAuthority   string `json:"mint_authority"`
        type: integer
    type: object
  parameters.PerformanceCreateSPLTokenRes:
    properties:
      mint_account:
        type: string
      signature:
        type: string
    type: object
  parameters.PerformanceMintReq:
    properties:
      amount:
        description: |-
          PayerPrivateKey string `json:"payer_private_key"`
          MintAccount     string `json:"mint_account"`
          MintAuthority   string `json:"mint_authority"`
        type: integer
    type: object
  parameters.PerformanceMintRes:
    properties:
      signature:
        type: string
    type: object
  parameters.TargetSolBalanceReq:
    properties:
      owner_account:
        type: string
    type: object
  parameters.TokenBalanceRes:
    properties:
      balance:
        type: string
      mint_account:
        type: string
      owner_account:
        type: string
    type: object
  parameters.TransferTokenReq:
    properties:
      amount:
        type: integer
    type: object
info:
  contact: {}
  description: This is a rest api server for solapi
  title: SOL API
  version: 1.0.0
paths:
  /account/balance:
    get:
      consumes:
      - application/json
      description: SOL Balance를 조회합니다
      parameters:
      - description: Get SOL Balance
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameters.TargetSolBalanceReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/parameters.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/parameters.TokenBalanceRes'
              type: object
      summary: solana balance query
      tags:
      - /account
  /spl/deploy:
    post:
      consumes:
      - application/json
      description: SPL Token을 생성합니다
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/parameters.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/parameters.PerformanceCreateSPLTokenRes'
              type: object
      summary: SPL Token 생성
      tags:
      - /spl
  /spl/deploy-with-mint:
    post:
      consumes:
      - application/json
      description: Token Account를 생성한 뒤 민팅합니다.
      parameters:
      - description: Performance Create SPL Token And Mint Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameters.CreateTokenWithMintReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/parameters.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/parameters.PerformanceCreateSPLTokenRes'
              type: object
      summary: Token Account 생성 후 민팅
      tags:
      - /spl
  /spl/mint:
    post:
      consumes:
      - application/json
      description: 배포 완료 상태에서 target wallet에 추가 민팅합니다.
      parameters:
      - description: Performance Create SPL Token Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameters.PerformanceMintReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/parameters.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/parameters.PerformanceMintRes'
              type: object
      summary: 민팅
      tags:
      - /spl
  /spl/query:
    get:
      consumes:
      - application/json
      description: Token Balance를 조회합니다
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/parameters.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/parameters.TokenBalanceRes'
              type: object
      summary: Token Query
      tags:
      - /spl
  /spl/set-mint-account:
    post:
      consumes:
      - application/json
      description: 기존 생성한 Mint Account에 deploy 후 민팅
      parameters:
      - description: Performance Create SPL Token And Mint Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameters.CreateTokenWithMintReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/parameters.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/parameters.PerformanceMintRes'
              type: object
      summary: 테스트 사전 준비
      tags:
      - /spl
  /spl/target_query:
    get:
      consumes:
      - application/json
      description: Token Balance를 조회합니다
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/parameters.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/parameters.TokenBalanceRes'
              type: object
      summary: Token Query
      tags:
      - /spl
  /spl/transfer:
    post:
      consumes:
      - application/json
      description: Token을 전송합니다.
      parameters:
      - description: Transfer SPL Token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameters.TransferTokenReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/parameters.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/parameters.PerformanceMintRes'
              type: object
      summary: Token Transfer
      tags:
      - /spl
swagger: "2.0"
