
spring:
  datasource:
    datasource-local:
      driver-class-name : com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3300/localapp
      username: root
      password: root
    datasource-test:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3300/testapp
      username: root
      password: root

